---
title: "Exploring eechidna"
output: html_notebook
---

```{r}
library(eechidna)
library(tidyverse)
library(readxl)
```

The census data is at the electorate level. It would be interesting to go down to the SLA level, so we can map polling booth statistics to SLA2 for more granularity

```{r}
census <- abs2016
election_2pp <- twoparty_pollingbooth_download()
election_2pp_2016 <- election %>%
  filter(year == 2016)
```

Maps from Di Cook and Jeremy Forbes' vignette
```{r}
stns <- read_csv("http://results.aec.gov.au/20499/Website/Downloads/GeneralPollingPlacesDownload-20499.csv", skip = 1)
library(ggthemes)
nat_map16 <- nat_map_download(2016)
nat_data16 <- nat_data_download(2016)

ggplot(data = nat_data16, aes(map_id = id)) +
  geom_map(
    map = nat_map16, fill = "grey90",
    colour = "white"
  ) +
  geom_point(
    data = stns, aes(x = Longitude, y = Latitude),
    colour = "red", size = 1, alpha = 0.3, inherit.aes = FALSE
  ) +
  xlim(c(
    112,
    157
  )) +
  ylim(c(-44, -11)) +
  theme_map() +
  coord_equal()
```

```{r tcp_map, fig.width=7, fig.height=5, message=FALSE, error = TRUE, warning=FALSE, echo=FALSE, tidy=TRUE}
tcp_pp <- twocand_pollingbooth_download()
tcp_pp16 <- tcp_pp %>% filter(year == 2016)
# Find winner
winners <- tcp_pp16 %>%
  left_join(tcp_pp16 %>% dplyr::group_by(PollingPlace, DivisionNm) %>% summarise(TotalVotes = sum(OrdinaryVotes)), by = c("PollingPlace", "DivisionNm")) %>%
  filter(OrdinaryVotes / TotalVotes > 0.5)
# Plot
ggplot(data = nat_data16, aes(map_id = id)) +
  geom_map(map = nat_map16, fill = "grey90", colour = "white") +
  geom_point(data = winners, aes(x = Longitude, y = Latitude, colour = PartyAb), size = 1, alpha = 0.6, inherit.aes = FALSE) +
  scale_color_manual("Party", values = c("LNP" = "#80b1d3", "ALP" = "#fb8072", "GRN" = "#33a02c", "XEN" = "#beaed4", "ON" = "#fdc086", "KAP" = "#ffff99", "IND" = "grey25")) +
  xlim(c(112, 157)) +
  ylim(c(-44, -11)) +
  theme_map() +
  coord_equal() +
  theme(legend.position = "bottom")
```

Download and load polling places by SA1
```{r}

download.file("https://www.aec.gov.au/Elections/Federal_Elections/2016/files/polling-place-by-sa1s-2016.xlsx", "./Data/polling-place-by-sa1s-2016.xlsx", method = "libcurl")

polling_place_data <- readxl::read_xlsx("./Data/polling-place-by-sa1s-2016.xlsx")

# library(repmis)
#
# centroids <- load("./Data/centroids_sa1_2001.rda")
# alloc_elec_16 <- allocate_electorate(centroids_sa1_2011, census_year = 2016, election_year = 2016)
```
